Update user-manual.rst example with missing line-end colon
Without this colon, using this code returns the error: `FATAL: main.py:3 Error, 'nuitka-project-if' needs to start a block with a colon at line end.`